### PR TITLE
Fix everything (WIP)

### PR DESCRIPTION
**Pull request by TechDudie**
its been a long time, ive decided to help out on this project :)

### CODE REVIEW

**Comment by TechDudie** [comment]
ok, everything is cleaned up, just need to test it

im thinking abount adding some extra fuels

**Comment by TechDudie** [comment]
For example, im gonna add methane, and imma fix propane

**Comment by pl608** [comment]
ok i think i got a propane tank model some where + texture
not the best though

**Comment by pl608** [comment]
there

**Pull request merged**
